# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit mpitbR.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(kableExtra)


## ----set, eval=FALSE----------------------------------------------------------
#> mpitb.set(data, indicators, ...,
#>           name = "unnamed", desc = "desc.")


## ----est, eval=FALSE----------------------------------------------------------
#> mpitb.est(set, klist = NULL, weights = "equal",
#>           measures = c("M0", "H", "A"),
#>           indmeasures = c("hd", "hdk", "actb", "pctb"),
#>           indklist = NULL,  over = NULL,  ...,
#>           cotyear = NULL,  tvar = NULL,
#>           cotmeasures = c("M0", "H", "A", "hd", "hdk"),
#>           ann = FALSE,  cotklist = NULL,
#>           cotoptions = "total",
#>           noraw = FALSE,  nooverall = FALSE,
#>           level = 0.95,
#>           multicore = getOption("mpitb.multicore"),
#>           verbose = TRUE)


## ----load_libraries, echo=TRUE, eval=TRUE-------------------------------------
library(survey)
library(mpitbR)


## ----svydata-tab-interactive, echo=FALSE--------------------------------------
knitr::kable(head(syn_cdta), format = "html", caption = "A synthetic household survey data") 


## ----svydata-tab-static, echo=FALSE-------------------------------------------
knitr::kable(head(syn_cdta), format = "latex",caption = "A synthetic household survey data") %>% 
  kable_styling(font_size = 7)


## ----define_survey_design, echo=TRUE------------------------------------------
# Subset data
syn_cdta1 <- subset(syn_cdta, t == 1)
# Drop NA in indicators columns
syn_cdta1 <- na.omit(syn_cdta1)
# Define survey design
svydata1 <- svydesign(id=~psu, weights = ~weight, strata = ~stratum, data = syn_cdta1)


## ----define_mpitb_set, eval=FALSE---------------------------------------------
#> indicators <- list(hl = c("d_nutr","d_cm"),
#>                    ed = c("d_satt","d_educ"),
#>                    ls = c("d_elct","d_sani","d_wtr","d_hsg","d_ckfl","d_asst"))
#> 
#> set.trial01 <- mpitb.set(svydata1, indicators = indicators,
#>                          name = "trial01", desc = "pref. spec")
#> 


## ----estimation1, echo=TRUE, eval=FALSE---------------------------------------
#> est.trial01 <- mpitb.est(set = set.trial01, klist = c(20, 33, 50),
#>                          weights = "equal",
#>                  measures = c("M0","H","A"),
#>                  indmeasures = c("hd", "hdk", "actb", "pctb"),
#>                  over = c("area","region"))


## ----eval=FALSE---------------------------------------------------------------
#> head(est.trial01$lframe)


## ----confint, eval=FALSE------------------------------------------------------
#> confint(subset(est.trial01$lframe, measure == "H" & loa == "area" & k == 20))


## ----avoid_estimations, eval=FALSE--------------------------------------------
#> mpitb.est(set = set.trial01, klist = c(20, 33, 50),
#>           weights = "equal", measures = c("M0"),
#>           indmeasures = c("hd", "hdk"), indklist = c(33),
#>           over = c("area","region"), nooverall = TRUE)


## ----eval = FALSE-------------------------------------------------------------
#> mpitb.est(set = set.trial01, klist = c(33),
#>           measures = c("M0"), indmeasures = NULL,
#>           weights = c(1/6, 1/6, 1/6, 1/6,
#>                       1/18, 1/18, 1/18, 1/18, 1/18, 1/18))


## ----eval = FALSE-------------------------------------------------------------
#> mpitb.est(set = set.trial01, klist = c(33),
#>           measures = c("M0"), indmeasures = NULL,
#>           weights = c(1/4, 1/4, 1/8, 1/8,
#>                       1/24, 1/24, 1/24, 1/24, 1/24, 1/24))


## ----dropout_elec, eval = FALSE-----------------------------------------------
#> indicators <- list(hl = c("d_nutr","d_cm"),
#>                    ed = c("d_satt","d_educ"),
#>                    ls = c("d_sani","d_wtr","d_hsg","d_ckfl","d_asst"))
#> 
#> set.trial02 <- mpitb.set(syn_cdta, indicators = indicators,
#>                  name = "trial02", desc = "w/o electricity")
#> 
#> est.trial02 <- mpitb.est(set = set.trial02, klist = c(20), weights = "equal",
#>                  measures = c("M0","H","A"),
#>                  indmeasures = c("hd", "hdk", "actb", "pctb"),
#>                  over = c("area","region"))


## ----define_survey_designCOT, echo=TRUE---------------------------------------
# Drop NA in indicators columns
syn_cdta <- na.omit(syn_cdta)
# Define survey design
svydata <- svydesign(id=~psu, weights = ~weight, strata = ~stratum, data = syn_cdta)


## ----define_mpitb_setCOT, eval=FALSE------------------------------------------
#> indicators <- list(hl = c("d_nutr","d_cm"),
#>                    ed = c("d_satt","d_educ"),
#>                    ls = c("d_elct","d_sani","d_wtr","d_hsg","d_ckfl","d_asst"))
#> 
#> set.trialCOT <- mpitb.set(svydata, indicators = indicators, name = "trialCOT", desc = "Estimate changes over time")
#> 


## ----estCOT, eval = FALSE-----------------------------------------------------
#> est.trialCOT <- mpitb.est(set = set.trialCOT, klist = c(1, 33, 50),
#>                  indmeasures = NULL,
#>                  over = c("region"), tvar = "t", cotyear = "year")

